[package]
name = "rasitop"
version = "0.1.0"
edition = "2024"
default-run = "rasitop"

[[bin]]
name = "rasitop-app"
path = "src/bin/rasitop-app.rs"
test = false
bench = false

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
clap = { version = "4.5.37", features = ["derive"] }
ctrlc = "3.5"
csv = "1.3"
humantime = "2.1"
serde = { version = "1.0.210", features = ["derive"] }
