[package]
name = "rasitop"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
clap = { version = "4.5.37", features = ["derive"] }
core-foundation = "0.10.1"
ctrlc = "3.5"
libc = "0.2.172"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.12"

[dev-dependencies]
insta = "1.41.1"
